[package]
name = "set-2-block-crypto"
version = "0.1.0"
authors = ["Carlos Rodriguez"]

[[bin]]
name = "challenge-9"
path = "src/9-implement-pkcs7-padding/main.rs"

[dependencies]
shared = { path = "../shared" }
